[package]
name = "QB-Add-Torrent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.12.15", features = ["cookies", "multipart", "stream"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["fs", "macros", "rt"] }
